name: eqiv-sc
version: 0.1.0.0
github: "BrandenXia/eqiv-sc"
license: BSD-3-Clause
author: "BrandenXia"
maintainer: "xxtbranden@outlook.com"
copyright: "2025 BrandenXia"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/BrandenXia/eqiv-sc#readme>

dependencies:
  - base >= 4.7 && < 5
  - vector >= 0.13.2.0
  - hashtables >= 1.4.2
  - hashable >= 1.5.0.0
  - containers >= 0.7
  - transformers >= 0.6.1.1
  - megaparsec >= 9.7.0
  - parser-combinators >= 1.3.0
  - text >= 2.1.2
  - haskeline >= 0.8.2.1
  - optparse-applicative >= 0.18.1.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: libs

executables:
  eqiv-sc-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - eqiv-sc

tests:
  eqiv-sc-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - eqiv-sc
